apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonapp-api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: ghcr.io/yogeshraheja/python-api:v2.27
        resources:
          limits:
            memory: "75Mi"
            cpu: "75m"
        ports:
        - containerPort: 8000
          name: pythonapp-api
        envFrom:
          - secretRef:
              name: db-connect
          - configMapRef:
              name: db-connect
