apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pythonapp-apiservice
  namespace: argocd
spec:
  destination:
    namespace: default
    name: in-cluster
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true

  project: default

  source:
    repoURL: https://github.com/yogeshraheja/Argo-CD-Capstone-Project.git
    path: manifests/apps/api
    targetRevision: main
