name: API Docker Image CI
on:
  push:
    branches: [ "main", "argocd-demo"  ]
    paths:
      - 'api/*'
      - '.github/workflows/docker-image-api.yml'
  pull_request:
    branches: [ "main", "argocd-demo" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build & PUSH the Docker image
      run: |
        cd api/
        docker image build . -f Dockerfile -t ghcr.io/yogeshraheja/python-api:v2.${{ github.run_number }}
        docker image push ghcr.io/yogeshraheja/python-api:v2.${{ github.run_number }}
        cp deployment.yaml ../manifests/apps/api/deployment.yaml
        sed -i 's/ImageTag/v2.${{ github.run_number }}/g' ../manifests/apps/api/deployment.yaml
        git config --global user.email "yogesh.raheja@thinknyx.com"
        git config --global user.name "Yogesh Raheja"
        git commit -am "Updated Image Version to v2.${{ github.run_number }}"
        git push origin ${{ github.ref }}
