name: API Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'api/*'
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build & PUSH the Docker image
      run: |
        cd api/
        docker image build . -f Dockerfile -t ghcr.io/kmayer10/python-api:v1
        docker image push ghcr.io/kmayer10/python-api:v1
