name: WEB Docker Image CI
on:
  push:
    branches: [ "main", "argocd-demo"  ]
    paths:
      - 'web/*'
      - '.github/workflows/docker-image-web.yml'
  pull_request:
    branches: [ "main", "argocd-demo" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build & PUSH the Docker image
      run: |
        cd web/
        docker image build . -f Dockerfile -t ghcr.io/kmayer10/python-web:v2.${{ github.run_number }}
        docker image push ghcr.io/kmayer10/python-web:v2.${{ github.run_number }}
        cp deployment.yaml ../manifests/apps/web/deployment.yaml
        sed -i 's/ImageTag/v2.${{ github.run_number }}/g' ../manifests/apps/web/deployment.yaml
        git config --global user.email "kulbhushan.mayer@gmail.com"
        git config --global user.name "Kulbhushan Mayer"
        git commit -am "Updated Image Version to v2.${{ github.run_number }}"
        git push origin argocd-demo
