name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker image build . -f python/Dockerfile -t python:latest
    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        registry: ghcr.io
        # Username used to log against the Docker registry
        username: ${{ secrets.DOCKER_USERNAME }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: PUSH to GHCR Repo
      run: | 
        docker image tag python:latest ghcr.io/kmayer10/python:latest
        docker image push ghcr.io/kmayer10/python:latest
      
        
